//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5477
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VinewatchX.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VinewatchX.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap _1324240144374 {
            get {
                object obj = ResourceManager.GetObject("_1324240144374", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bigger_icon {
            get {
                object obj = ResourceManager.GetObject("bigger_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream calm_down {
            get {
                return ResourceManager.GetStream("calm_down", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream easteregg {
            get {
                return ResourceManager.GetStream("easteregg", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream fantasy {
            get {
                return ResourceManager.GetStream("fantasy", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap hannibal {
            get {
                object obj = ResourceManager.GetObject("hannibal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InternalResource.
        /// </summary>
        internal static string iconStatus {
            get {
                return ResourceManager.GetString("iconStatus", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon live {
            get {
                object obj = ResourceManager.GetObject("live", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Mango {
            get {
                object obj = ResourceManager.GetObject("Mango", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream MANGO1 {
            get {
                return ResourceManager.GetStream("MANGO1", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream notify_smtdsmts {
            get {
                return ResourceManager.GetStream("notify_smtdsmts", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream notify_van {
            get {
                return ResourceManager.GetStream("notify_van", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap OvYVTBc {
            get {
                object obj = ResourceManager.GetObject("OvYVTBc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon vs {
            get {
                object obj = ResourceManager.GetObject("vs", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon vw {
            get {
                object obj = ResourceManager.GetObject("vw", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
